export const Tech = {
  React: { name: 'React', displayName: 'React' },
  TypeScript: { name: 'TypeScript', displayName: 'TypeScript' },
  Redux: { name: 'Redux', displayName: 'Redux' },
  Node: { name: 'Node', displayName: 'Node' },
  MongoDb: { name: 'MongoDb', displayName: 'Mongo DB' },
  Es6: { name: 'Es6', displayName: 'ES6' },
  Xamarin: { name: 'Xamarin', displayName: 'Xamarin' },
  Aws: { name: 'Aws', displayName: 'AWS' },
  Atlassian: { name: 'Atlassian', displayName: 'Atlassian' },
  TeamCity: { name: 'TeamCity', displayName: 'TeamCity' },
  Heroku: { name: 'Heroku', displayName: 'Heroku' },
  Braze: { name: 'Braze', displayName: 'Braze' },
  Firebase: { name: 'Firebase', displayName: 'Firebase' },
  Angular: { name: 'Angular', displayName: 'Angular' },
  Figma: { name: 'Figma', displayName: 'Figma' },
  Apollo: { name: 'Apollo', displayName: 'Apollo' },
  GraphQL: { name: 'GraphQL', displayName: 'GraphQL' },
  Html5: { name: 'Html5', displayName: 'HTML 5' },
  Css3: { name: 'Css3', displayName: 'CSS 3' },
  JQuery: { name: 'JQuery', displayName: 'JQuery' },
  CSharp: { name: 'CSharp', displayName: 'C#' },
  Java: { name: 'Java', displayName: 'Java' },
  Sql: { name: 'Sql', displayName: 'SQL' },
  VisualStudio: { name: 'VisualStudio', displayName: 'Visual Studio' },
  VsCode: { name: 'VsCode', displayName: 'VS Code' },
  DotNetCore: { name: 'DotNetCore', displayName: '.NET Core' },
  JavaScript: { name: 'JavaScript', displayName: 'JavaScript' },
  MySql: { name: 'MySql', displayName: 'MySql' },
  Android: { name: 'Android', displayName: 'Android' },
  IOs: { name: 'IOs', displayName: 'iOS' },
  Yarn: { name: 'Yarn', displayName: 'yarn' }
};
