name: fluffy oyster cicd

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'

jobs:
  cicd:
    name: deploy to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: setup node.js for use with actions
          uses: actions/setup-node@v1.1.0
          with:
            version:  16.x

      - name: checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: install yarn
        run: npm install -g yarn

      - name: install dependencies
        run: yarn build

      - name: predeploy
        run: npm run build

      - name: Deploy
        run: |
          git config user.name "nkuznetsov" && git config user.email "kuznetsov.nikita@gmail.com"
          npm run gh-pages-deploy
    env:
      GIT_AUTHOR_NAME: nkuznetsov
